[package]
name = "respk-cli"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "ResPK CLI"
edition = "2018"

[dependencies]
getopts = "0.2"
walkdir = "2"

[dependencies.respk]
path = ".."
